This is a fork of the C# yacc used by the mono C# compiler.

The original mono version can be found here:
	https://github.com/mono/mono/tree/master/mcs/jay

The mono version was a fork of Jay, a java port of Berkeley Yacc.  The original Jay can be found here:
	http://www.informatik.uni-osnabrueck.de/bernd/jay/

This project is distributed with no warranty whatever.  The code is certain
to contain errors.  Neither the author nor any contributor takes responsibility
for any consequences of its use.

This project is in the public domain.  The data structures and algorithms
used in cs-yacc are all either taken from documents available to the
general public or are inventions of the author.  Anyone may freely distribute
source or binary forms of cs-yacc whether unchanged or modified.
Distributers may charge whatever fees they can obtain for cs-yacc.
Programs generated by cs-yacc may be distributed freely.